# Generated by Django 4.2.5 on 2023-10-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50)),
                ('spec', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phnno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='postvacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jobtitle', models.CharField(max_length=20)),
                ('wrktype', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=30)),
                ('jobtype', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phnno', models.IntegerField()),
            ],
        ),
    ]
