# Generated by Django 4.2.5 on 2023-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0002_post_postvacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherregmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=20)),
                ('phnno', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
