# Generated by Django 4.2.5 on 2023-10-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0005_rename_phnno_teacherregmodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='phnno',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='postvacancy',
            old_name='phnno',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='postvacancy',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='postvacancy',
            name='eligibility',
            field=models.CharField(max_length=1000),
        ),
    ]
