# Generated by Django 4.2.5 on 2023-10-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0006_rename_phnno_post_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='postmodel',
        ),
        migrations.RenameModel(
            old_name='postvacancy',
            new_name='postvacancymodel',
        ),
    ]
