# Generated by Django 4.2.5 on 2023-10-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0007_rename_post_postmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvacancymodel',
            name='phone',
        ),
    ]
