# Generated by Django 4.2.5 on 2023-10-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0008_remove_postvacancymodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvacancymodel',
            name='salary',
        ),
    ]
