# Generated by Django 4.2.5 on 2023-10-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0009_remove_postvacancymodel_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='postvacmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jobtitle', models.CharField(max_length=20)),
                ('wrktype', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=30)),
                ('jobtype', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='postmodel',
            new_name='postcoursemodel',
        ),
        migrations.DeleteModel(
            name='postvacancymodel',
        ),
    ]
