# Generated by Django 4.2.5 on 2023-11-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0010_postvacmodel_rename_postmodel_postcoursemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyvacmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('jobtitle', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('quali', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('resume', models.FileField(upload_to='jobapp/static')),
            ],
        ),
    ]
