# Generated by Django 4.2.5 on 2023-11-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0011_applyvacmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='applycoursemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('spec', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('quali', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('certi', models.FileField(upload_to='jobapp/static')),
            ],
        ),
    ]
