# Generated by Django 4.2.5 on 2023-11-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admiss', '0012_applycoursemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='apprejmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('quali', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=20)),
                ('jobtitle', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('apprej', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='applycoursemodel',
            name='certi',
            field=models.FileField(upload_to='admiss/static'),
        ),
        migrations.AlterField(
            model_name='applyvacmodel',
            name='resume',
            field=models.FileField(upload_to='admiss/static'),
        ),
    ]
